-- PROGRESSION - 1

-- 1. **Create table city**
CREATE TABLE CITY
( ID NUMBER(11)NOT NULL,
  NAME VARCHAR(40) NOT NULL,
  CONSTRAINT CITY_PK PRIMARY KEY (ID)
);
DROP TABLE CITY;
SELECT * FROM CITY;



-- 2. **Create table referee**
CREATE TABLE REFEREE
( ID NUMBER(11)NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  CONSTRAINT REFERENCE PRIMARY KEY (ID)
);

-- 3. **Create table innings**
CREATE TABLE INNINGS
( ID NUMBER(11)NOT NULL,
  INNINGS_NUMBER NUMBER(11) NOT NULL,
  CONSTRAINT INNINGS PRIMARY KEY (ID)
);

-- 4. **Create table extra_type**
CREATE TABLE EXTRA_TYPE
( ID NUMBER(11)NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  CONSTRAINT EXTRA_TYPE  PRIMARY KEY (ID)
);

-- 5. **Create table skill**
CREATE TABLE SKILL
( ID NUMBER(11)NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  CONSTRAINT SKILL  PRIMARY KEY (ID)
);

select * from skill ;
drop table skill;

-- 6. **Create table team**
CREATE TABLE TEAM
( ID NUMBER(11),
  NAME VARCHAR(50) NOT NULL,
  COACH VARCHAR(50) NOT NULL,
  CAPTIAN NUMBER(11),
  HOME_CITY NUMBER(11),
  CONSTRAINT fk_CITY
    FOREIGN KEY (HOME_CITY)
    REFERENCES CITY(ID),
  CONSTRAINT TEAM PRIMARY KEY(ID)
);

ALTER TABLE  TEAM DROP CONSTRAINT fk_CITY;
DROP TABLE TEAM;
SELECT *FROM TEAM;
-- 7. **Create table player**
CREATE TABLE PLAYER
( ID NUMBER(11),
  NAME VARCHAR(50) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL,
  CAPTIAN NUMBER(11),
  SKILL_ID NUMBER(11),
  CONSTRAINT FK_SKILL
    FOREIGN KEY (SKILL_ID)
    REFERENCES SKILL(ID),
    TEAM_ID NUMBER(11),
  CONSTRAINT FK_TEAM
    FOREIGN KEY (TEAM_ID)
    REFERENCES TEAM(ID),
  CONSTRAINT PLAYERS PRIMARY KEY(ID)
);

ALTER TABLE  PLAYER DROP CONSTRAINT FK_SKILL;
ALTER TABLE  PLAYER DROP CONSTRAINT FK_TEAM;
DROP TABLE PLAYER;
SELECT * FROM PLAYER;

-- 8. **Create table venue**
CREATE TABLE VENUE
( VENUE_ID NUMBER(11),
  STADIUM_NAME VARCHAR(50) NOT NULL,
  CITY_ID NUMBER(11),
  CONSTRAINT FK_CITYID
    FOREIGN KEY (CITY_ID)
    REFERENCES CITY(ID),
  CONSTRAINT VENUE PRIMARY KEY(VENUE_ID)  
); 
SELECT * FROM VENUE;
ALTER TABLE  VENUE DROP CONSTRAINT FK_CITYID;
DROP TABLE VENUE;

-- 9. **Create table event**
CREATE TABLE EVENT
( ID NUMBER(11)NOT NULL,
  EVENT_NUMBER NUMBER(11)NOT NULL,
  RAID_POINTS NUMBER(11)NOT NULL,
  DEFENDING_POINTS NUMBER(11)NOT NULL,
  CLOCK_SECOUNDS NUMBER(11)NOT NULL,
   TEAM_ONE_SCORE NUMBER(11)NOT NULL,
   TEAM_TWO_SCORE NUMBER(11)NOT NULL,
   INNINGS_ID NUMBER(11) NOT NULL,
   CONSTRAINT FK_INNINGS
    FOREIGN KEY (INNINGS_ID)
    REFERENCES INNINGS(ID),
    RAIDER_ID NUMBER(11),
    CONSTRAINT FK_PLAYER
    FOREIGN KEY (RAIDER_ID)
    REFERENCES PLAYER(ID),
  CONSTRAINT EVENT_PK  PRIMARY KEY (ID)
);
SELECT * FROM EVENT;
ALTER TABLE  EVENT DROP CONSTRAINT  FK_PLAYER;

ALTER TABLE  EVENT DROP CONSTRAINT FK_innings;
DROP TABLE EVENT;

-- 10. **Create table extra_event**
CREATE TABLE EXTRA_EVENT
( ID NUMBER(11)NOT NULL,
  STADIUM_NAME VARCHAR(50) NOT NULL,
  POINTS NUMBER(11)NOT NULL,
  EVENT_ID NUMBER(11)NOT NULL,
  CONSTRAINT FK_EVENT
    FOREIGN KEY (EVENT_ID)
    REFERENCES EVENT(ID),
     EXTRA_TYPE_ID NUMBER(11)NOT NULL,
  CONSTRAINT FK_EXTRA_TYPE
    FOREIGN KEY (EXTRA_TYPE_ID)
    REFERENCES EXTRA_TYPE(ID),
     SCORING_TEAM_ID NUMBER(11)NOT NULL,
  CONSTRAINT FK_SCORING_TEAM
    FOREIGN KEY (SCORING_TEAM_ID)
    REFERENCES TEAM(ID),
  CONSTRAINT EXTRA_EVENT_PK PRIMARY KEY(ID)  
);

SELECT *FROM EXTRA_EVENT;
ALTER TABLE  EXTRA_EVENT DROP CONSTRAINT FK_EVENT;
-- 11. **Create table outcome**
CREATE TABLE OUTCOME
( ID NUMBER(11)NOT NULL,
 STATUS VARCHAR(100) NOT NULL,
 SCORE NUMBER(11),
  WINNER_TEAM_ID NUMBER(11),
  CONSTRAINT FK_WINNERTEAMID
    FOREIGN KEY (WINNER_TEAM_ID)
    REFERENCES TEAM(ID),
    PLAYER_OF_MATCH NUMBER(11),
  CONSTRAINT FK_PLAYEROFMATCH
    FOREIGN KEY (PLAYER_OF_MATCH)
    REFERENCES PLAYER(ID),  
  CONSTRAINT OUTCOME_PK PRIMARY KEY(ID)  
);

SELECT *FROM OUTCOME;
-- 12. **Create table game**
CREATE TABLE GAME
( ID NUMBER(11)NOT NULL,
 GAME_DATE DATE NOT NULL,
 
 TEAM_ID_ONE NUMBER(11)NOT NULL,
  CONSTRAINT FK_TEAMID1
    FOREIGN KEY (TEAM_ID_ONE)
    REFERENCES TEAM(ID),
    
    
    VENUE_ID NUMBER(11)NOT NULL,
  CONSTRAINT FK_VENUEID
    FOREIGN KEY (VENUE_ID)
    REFERENCES VENUE(ID),  
    
    OUTCOME_ID NUMBER(11)NOT NULL,
  CONSTRAINT FK_OUTCOMEID
    FOREIGN KEY (OUTCOME_ID)
    REFERENCES OUTCOME(ID),  
    
    REFERNECE_ID NUMBER(11)NOT NULL,
  CONSTRAINT FK_REFERENCEID
    FOREIGN KEY (REFERENCE_ID)
    REFERENCES REFERENCE(ID), 
    
    FIRST_INNINGS_ID NUMBER(11)NOT NULL,
  CONSTRAINT FK_FIRSTINNINGSID
    FOREIGN KEY (FIRST_INNINGS_ID)
    REFERENCES INNINGS(ID),  
    
    
  CONSTRAINT GAME_PK PRIMARY KEY(ID)  
);
-- 13. **Drop table city**
ALTER TABLE  TEAM DROP CONSTRAINT fk_CITY;
ALTER TABLE  VENUE DROP CONSTRAINT FK_CITYID;
DROP TABLE CITY;

-- 14. **Drop table innings**
ALTER TABLE  EVENT DROP CONSTRAINT FK_INNINGS;
DROP TABLE INNINGS;

-- 15. **Drop table skill**
ALTER TABLE  PLAYER DROP CONSTRAINT FK_SKILL;
DROP TABLE SKILL;

-- 16. **Drop table extra_type**
ALTER TABLE EXTRA_EVENT DROP CONSTRAINT FK_EXTRA_TYPE;
DROP TABLE EXTRA_TYPE;
